name: Setup Java
description: Configura Java 21 (GraalVM CE) con cache de Gradle

runs:
  using: composite
  steps:
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: "21"
        distribution: graalvm-community
        cache: gradle

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2
      with:
        min-wrapper-count: 1
