apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: agromis-db-credentials
  namespace: agromis-staging
spec:
  refreshInterval: 1m

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: agromis-db-credentials   # Secret K8s que se crea
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        QUARKUS_DATASOURCE_JDBC_URL: >-
          jdbc:postgresql://{{ .host }}:{{ .port }}/{{ .dbname }}
        QUARKUS_DATASOURCE_USERNAME: "{{ .username }}"
        QUARKUS_DATASOURCE_PASSWORD: "{{ .password }}"

  data:
    - secretKey: host
      remoteRef:
        key: agromis/staging/rds
        property: host
    - secretKey: port
      remoteRef:
        key: agromis/staging/rds
        property: port
    - secretKey: dbname
      remoteRef:
        key: agromis/staging/rds
        property: dbname
    - secretKey: username
      remoteRef:
        key: agromis/staging/rds
        property: username
    - secretKey: password
      remoteRef:
        key: agromis/staging/rds
        property: password
